{{- if .Values.persistance.config.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wyoming-piper.fullname" . }}-pvc
  labels:
    {{- include "wyoming-piper.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistance.config.storageClass }}
  accessModes: {{ .Values.persistance.config.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistance.config.size }}
{{- end }}